const std = @import("std");
const bindings = @import("bindings");

pub const geometry = @import("v4l2/geometry.zig");
pub const pixel = @import("v4l2/pixel.zig");
pub const buffer = @import("v4l2/buffer.zig");
pub const capability = @import("v4l2/capability.zig");
pub const frame = @import("v4l2/frame.zig");
pub const stream = @import("v4l2/stream.zig");
pub const standard = @import("v4l2/standard.zig");
pub const timings = @import("v4l2/timings.zig");
pub const input = @import("v4l2/input.zig");
pub const output = @import("v4l2/output.zig");
pub const control = @import("v4l2/control.zig");
pub const tuner = @import("v4l2/tuner.zig");
pub const audio = @import("v4l2/audio.zig");
pub const encoder = @import("v4l2/encoder.zig");
pub const decoder = @import("v4l2/decoder.zig");
pub const vbi = @import("v4l2/vbi.zig");
pub const event = @import("v4l2/event.zig");
pub const media = @import("v4l2/media.zig");
pub const mediabus = @import("v4l2/mediabus.zig");
pub const subdev = @import("v4l2/subdev.zig");
pub const debug = @import("v4l2/debug.zig");
pub const camera = @import("v4l2/control/camera.zig");
pub const class = @import("v4l2/control/class.zig");
pub const core = @import("v4l2/control/core.zig");
pub const cx2341x = @import("v4l2/control/cx2341x.zig");
pub const detect = @import("v4l2/control/detect.zig");
pub const dv = @import("v4l2/control/dv.zig");
pub const flash = @import("v4l2/control/flash.zig");
pub const fm = @import("v4l2/control/fm.zig");
pub const image = @import("v4l2/control/image.zig");
pub const jpeg = @import("v4l2/control/jpeg.zig");
pub const mfc51 = @import("v4l2/control/mfc51.zig");
pub const mpeg = @import("v4l2/control/mpeg.zig");
pub const rf_tuner = @import("v4l2/control/rf_tuner.zig");
pub const user = @import("v4l2/control/user.zig");
pub const av1 = @import("v4l2/control/stateless/av1.zig");
pub const fwht = @import("v4l2/control/stateless/fwht.zig");
pub const mpeg2 = @import("v4l2/control/stateless/mpeg2.zig");
pub const h264 = @import("v4l2/control/stateless/h264.zig");
pub const hevc = @import("v4l2/control/stateless/hevc.zig");
pub const vp8 = @import("v4l2/control/stateless/vp8.zig");
pub const vp9 = @import("v4l2/control/stateless/vp9.zig");
pub const abi = @import("v4l2/abi.zig");
pub const ioctl = @import("v4l2/ioctl.zig");
pub const base_vidioc_private = ioctl.base_vidioc_private;
pub const io = ioctl.io;
pub const ior = ioctl.ior;
pub const iow = ioctl.iow;
pub const iowr = ioctl.iowr;
pub const Ioctl = ioctl.Ioctl;

comptime {
    std.testing.refAllDecls(@This());
}
